#.travis.yml

language: node_js
node_js:
  - "6.9"
 
branches:
  only:
    - master
   
before_script:
  - npm install webpack
  - npm install -g firebase-tools
  - npm install -g @angular/cli
  
script:
  - webpack --progress

after_success:
  - firebase deploy --token $FIREBASE_TOKEN
 
notifications:
  email:
    on_failure: change
    on_success: change
